namespace Undefined.Mods;

public enum Category
{
    Main,
    Settings,
    MenuSettings,
    Themes,
    ThemeColors,
    CustomColors,
    ButtonTypes,
    SpecialMenu,
    EnabledMods,
    FavouriteMods,
    RoomMods,
    MovementMods,
    FunMods,
    RigMods,
    VisualMods,
    SafetyMods,
    AdvantagesMods,
    MapLoader,
    SoundSpamMods,
    GuardianMods,
    MasterMods,
    SoundBoard,
    OverpoweredMods,
    NetworkedMods,
    DiscordRPC,
    Admin,
    SuperAdmin,
}